### ISSUE TITLE
Convert Reason record to TypeScript interface with the first letter being uppercased

### ISSUE THREAD

**Issue by nikgraf** [cristianoc/genTypeScript#4]
In TypeScript it's common that the first character of types and interfaces is upper-case.

Reason
```js
type person = { name: string };
```

Ideally would be converted to

```ts
interface Person { name: string };
```

Why Interfaces? They offer more capabilities compared to a type declaration e.g. extending them.

**Comment by cristianoc** [comment]
moved to genFlow/genType.
